// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quota.proto

#ifndef PROTOBUF_quota_2eproto__INCLUDED
#define PROTOBUF_quota_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "mesos.pb.h"
// @@protoc_insertion_point(includes)

namespace mesos {
namespace quota {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_quota_2eproto();
void protobuf_AssignDesc_quota_2eproto();
void protobuf_ShutdownFile_quota_2eproto();

class QuotaInfo;
class QuotaRequest;
class QuotaStatus;

// ===================================================================

class QuotaInfo : public ::google::protobuf::Message {
 public:
  QuotaInfo();
  virtual ~QuotaInfo();

  QuotaInfo(const QuotaInfo& from);

  inline QuotaInfo& operator=(const QuotaInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QuotaInfo& default_instance();

  void Swap(QuotaInfo* other);

  // implements Message ----------------------------------------------

  QuotaInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QuotaInfo& from);
  void MergeFrom(const QuotaInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string role = 1;
  inline bool has_role() const;
  inline void clear_role();
  static const int kRoleFieldNumber = 1;
  inline const ::std::string& role() const;
  inline void set_role(const ::std::string& value);
  inline void set_role(const char* value);
  inline void set_role(const char* value, size_t size);
  inline ::std::string* mutable_role();
  inline ::std::string* release_role();
  inline void set_allocated_role(::std::string* role);

  // optional string principal = 2;
  inline bool has_principal() const;
  inline void clear_principal();
  static const int kPrincipalFieldNumber = 2;
  inline const ::std::string& principal() const;
  inline void set_principal(const ::std::string& value);
  inline void set_principal(const char* value);
  inline void set_principal(const char* value, size_t size);
  inline ::std::string* mutable_principal();
  inline ::std::string* release_principal();
  inline void set_allocated_principal(::std::string* principal);

  // repeated .mesos.Resource guarantee = 3;
  inline int guarantee_size() const;
  inline void clear_guarantee();
  static const int kGuaranteeFieldNumber = 3;
  inline const ::mesos::Resource& guarantee(int index) const;
  inline ::mesos::Resource* mutable_guarantee(int index);
  inline ::mesos::Resource* add_guarantee();
  inline const ::google::protobuf::RepeatedPtrField< ::mesos::Resource >&
      guarantee() const;
  inline ::google::protobuf::RepeatedPtrField< ::mesos::Resource >*
      mutable_guarantee();

  // @@protoc_insertion_point(class_scope:mesos.quota.QuotaInfo)
 private:
  inline void set_has_role();
  inline void clear_has_role();
  inline void set_has_principal();
  inline void clear_has_principal();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* role_;
  ::std::string* principal_;
  ::google::protobuf::RepeatedPtrField< ::mesos::Resource > guarantee_;
  friend void  protobuf_AddDesc_quota_2eproto();
  friend void protobuf_AssignDesc_quota_2eproto();
  friend void protobuf_ShutdownFile_quota_2eproto();

  void InitAsDefaultInstance();
  static QuotaInfo* default_instance_;
};
// -------------------------------------------------------------------

class QuotaRequest : public ::google::protobuf::Message {
 public:
  QuotaRequest();
  virtual ~QuotaRequest();

  QuotaRequest(const QuotaRequest& from);

  inline QuotaRequest& operator=(const QuotaRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QuotaRequest& default_instance();

  void Swap(QuotaRequest* other);

  // implements Message ----------------------------------------------

  QuotaRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QuotaRequest& from);
  void MergeFrom(const QuotaRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool force = 1 [default = false];
  inline bool has_force() const;
  inline void clear_force();
  static const int kForceFieldNumber = 1;
  inline bool force() const;
  inline void set_force(bool value);

  // optional string role = 2;
  inline bool has_role() const;
  inline void clear_role();
  static const int kRoleFieldNumber = 2;
  inline const ::std::string& role() const;
  inline void set_role(const ::std::string& value);
  inline void set_role(const char* value);
  inline void set_role(const char* value, size_t size);
  inline ::std::string* mutable_role();
  inline ::std::string* release_role();
  inline void set_allocated_role(::std::string* role);

  // repeated .mesos.Resource guarantee = 3;
  inline int guarantee_size() const;
  inline void clear_guarantee();
  static const int kGuaranteeFieldNumber = 3;
  inline const ::mesos::Resource& guarantee(int index) const;
  inline ::mesos::Resource* mutable_guarantee(int index);
  inline ::mesos::Resource* add_guarantee();
  inline const ::google::protobuf::RepeatedPtrField< ::mesos::Resource >&
      guarantee() const;
  inline ::google::protobuf::RepeatedPtrField< ::mesos::Resource >*
      mutable_guarantee();

  // @@protoc_insertion_point(class_scope:mesos.quota.QuotaRequest)
 private:
  inline void set_has_force();
  inline void clear_has_force();
  inline void set_has_role();
  inline void clear_has_role();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* role_;
  ::google::protobuf::RepeatedPtrField< ::mesos::Resource > guarantee_;
  bool force_;
  friend void  protobuf_AddDesc_quota_2eproto();
  friend void protobuf_AssignDesc_quota_2eproto();
  friend void protobuf_ShutdownFile_quota_2eproto();

  void InitAsDefaultInstance();
  static QuotaRequest* default_instance_;
};
// -------------------------------------------------------------------

class QuotaStatus : public ::google::protobuf::Message {
 public:
  QuotaStatus();
  virtual ~QuotaStatus();

  QuotaStatus(const QuotaStatus& from);

  inline QuotaStatus& operator=(const QuotaStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const QuotaStatus& default_instance();

  void Swap(QuotaStatus* other);

  // implements Message ----------------------------------------------

  QuotaStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const QuotaStatus& from);
  void MergeFrom(const QuotaStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .mesos.quota.QuotaInfo infos = 1;
  inline int infos_size() const;
  inline void clear_infos();
  static const int kInfosFieldNumber = 1;
  inline const ::mesos::quota::QuotaInfo& infos(int index) const;
  inline ::mesos::quota::QuotaInfo* mutable_infos(int index);
  inline ::mesos::quota::QuotaInfo* add_infos();
  inline const ::google::protobuf::RepeatedPtrField< ::mesos::quota::QuotaInfo >&
      infos() const;
  inline ::google::protobuf::RepeatedPtrField< ::mesos::quota::QuotaInfo >*
      mutable_infos();

  // @@protoc_insertion_point(class_scope:mesos.quota.QuotaStatus)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::mesos::quota::QuotaInfo > infos_;
  friend void  protobuf_AddDesc_quota_2eproto();
  friend void protobuf_AssignDesc_quota_2eproto();
  friend void protobuf_ShutdownFile_quota_2eproto();

  void InitAsDefaultInstance();
  static QuotaStatus* default_instance_;
};
// ===================================================================


// ===================================================================

// QuotaInfo

// optional string role = 1;
inline bool QuotaInfo::has_role() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void QuotaInfo::set_has_role() {
  _has_bits_[0] |= 0x00000001u;
}
inline void QuotaInfo::clear_has_role() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void QuotaInfo::clear_role() {
  if (role_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    role_->clear();
  }
  clear_has_role();
}
inline const ::std::string& QuotaInfo::role() const {
  // @@protoc_insertion_point(field_get:mesos.quota.QuotaInfo.role)
  return *role_;
}
inline void QuotaInfo::set_role(const ::std::string& value) {
  set_has_role();
  if (role_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    role_ = new ::std::string;
  }
  role_->assign(value);
  // @@protoc_insertion_point(field_set:mesos.quota.QuotaInfo.role)
}
inline void QuotaInfo::set_role(const char* value) {
  set_has_role();
  if (role_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    role_ = new ::std::string;
  }
  role_->assign(value);
  // @@protoc_insertion_point(field_set_char:mesos.quota.QuotaInfo.role)
}
inline void QuotaInfo::set_role(const char* value, size_t size) {
  set_has_role();
  if (role_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    role_ = new ::std::string;
  }
  role_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mesos.quota.QuotaInfo.role)
}
inline ::std::string* QuotaInfo::mutable_role() {
  set_has_role();
  if (role_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    role_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:mesos.quota.QuotaInfo.role)
  return role_;
}
inline ::std::string* QuotaInfo::release_role() {
  clear_has_role();
  if (role_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = role_;
    role_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void QuotaInfo::set_allocated_role(::std::string* role) {
  if (role_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete role_;
  }
  if (role) {
    set_has_role();
    role_ = role;
  } else {
    clear_has_role();
    role_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:mesos.quota.QuotaInfo.role)
}

// optional string principal = 2;
inline bool QuotaInfo::has_principal() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void QuotaInfo::set_has_principal() {
  _has_bits_[0] |= 0x00000002u;
}
inline void QuotaInfo::clear_has_principal() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void QuotaInfo::clear_principal() {
  if (principal_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    principal_->clear();
  }
  clear_has_principal();
}
inline const ::std::string& QuotaInfo::principal() const {
  // @@protoc_insertion_point(field_get:mesos.quota.QuotaInfo.principal)
  return *principal_;
}
inline void QuotaInfo::set_principal(const ::std::string& value) {
  set_has_principal();
  if (principal_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    principal_ = new ::std::string;
  }
  principal_->assign(value);
  // @@protoc_insertion_point(field_set:mesos.quota.QuotaInfo.principal)
}
inline void QuotaInfo::set_principal(const char* value) {
  set_has_principal();
  if (principal_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    principal_ = new ::std::string;
  }
  principal_->assign(value);
  // @@protoc_insertion_point(field_set_char:mesos.quota.QuotaInfo.principal)
}
inline void QuotaInfo::set_principal(const char* value, size_t size) {
  set_has_principal();
  if (principal_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    principal_ = new ::std::string;
  }
  principal_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mesos.quota.QuotaInfo.principal)
}
inline ::std::string* QuotaInfo::mutable_principal() {
  set_has_principal();
  if (principal_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    principal_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:mesos.quota.QuotaInfo.principal)
  return principal_;
}
inline ::std::string* QuotaInfo::release_principal() {
  clear_has_principal();
  if (principal_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = principal_;
    principal_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void QuotaInfo::set_allocated_principal(::std::string* principal) {
  if (principal_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete principal_;
  }
  if (principal) {
    set_has_principal();
    principal_ = principal;
  } else {
    clear_has_principal();
    principal_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:mesos.quota.QuotaInfo.principal)
}

// repeated .mesos.Resource guarantee = 3;
inline int QuotaInfo::guarantee_size() const {
  return guarantee_.size();
}
inline void QuotaInfo::clear_guarantee() {
  guarantee_.Clear();
}
inline const ::mesos::Resource& QuotaInfo::guarantee(int index) const {
  // @@protoc_insertion_point(field_get:mesos.quota.QuotaInfo.guarantee)
  return guarantee_.Get(index);
}
inline ::mesos::Resource* QuotaInfo::mutable_guarantee(int index) {
  // @@protoc_insertion_point(field_mutable:mesos.quota.QuotaInfo.guarantee)
  return guarantee_.Mutable(index);
}
inline ::mesos::Resource* QuotaInfo::add_guarantee() {
  // @@protoc_insertion_point(field_add:mesos.quota.QuotaInfo.guarantee)
  return guarantee_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::mesos::Resource >&
QuotaInfo::guarantee() const {
  // @@protoc_insertion_point(field_list:mesos.quota.QuotaInfo.guarantee)
  return guarantee_;
}
inline ::google::protobuf::RepeatedPtrField< ::mesos::Resource >*
QuotaInfo::mutable_guarantee() {
  // @@protoc_insertion_point(field_mutable_list:mesos.quota.QuotaInfo.guarantee)
  return &guarantee_;
}

// -------------------------------------------------------------------

// QuotaRequest

// optional bool force = 1 [default = false];
inline bool QuotaRequest::has_force() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void QuotaRequest::set_has_force() {
  _has_bits_[0] |= 0x00000001u;
}
inline void QuotaRequest::clear_has_force() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void QuotaRequest::clear_force() {
  force_ = false;
  clear_has_force();
}
inline bool QuotaRequest::force() const {
  // @@protoc_insertion_point(field_get:mesos.quota.QuotaRequest.force)
  return force_;
}
inline void QuotaRequest::set_force(bool value) {
  set_has_force();
  force_ = value;
  // @@protoc_insertion_point(field_set:mesos.quota.QuotaRequest.force)
}

// optional string role = 2;
inline bool QuotaRequest::has_role() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void QuotaRequest::set_has_role() {
  _has_bits_[0] |= 0x00000002u;
}
inline void QuotaRequest::clear_has_role() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void QuotaRequest::clear_role() {
  if (role_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    role_->clear();
  }
  clear_has_role();
}
inline const ::std::string& QuotaRequest::role() const {
  // @@protoc_insertion_point(field_get:mesos.quota.QuotaRequest.role)
  return *role_;
}
inline void QuotaRequest::set_role(const ::std::string& value) {
  set_has_role();
  if (role_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    role_ = new ::std::string;
  }
  role_->assign(value);
  // @@protoc_insertion_point(field_set:mesos.quota.QuotaRequest.role)
}
inline void QuotaRequest::set_role(const char* value) {
  set_has_role();
  if (role_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    role_ = new ::std::string;
  }
  role_->assign(value);
  // @@protoc_insertion_point(field_set_char:mesos.quota.QuotaRequest.role)
}
inline void QuotaRequest::set_role(const char* value, size_t size) {
  set_has_role();
  if (role_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    role_ = new ::std::string;
  }
  role_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mesos.quota.QuotaRequest.role)
}
inline ::std::string* QuotaRequest::mutable_role() {
  set_has_role();
  if (role_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    role_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:mesos.quota.QuotaRequest.role)
  return role_;
}
inline ::std::string* QuotaRequest::release_role() {
  clear_has_role();
  if (role_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = role_;
    role_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void QuotaRequest::set_allocated_role(::std::string* role) {
  if (role_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete role_;
  }
  if (role) {
    set_has_role();
    role_ = role;
  } else {
    clear_has_role();
    role_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:mesos.quota.QuotaRequest.role)
}

// repeated .mesos.Resource guarantee = 3;
inline int QuotaRequest::guarantee_size() const {
  return guarantee_.size();
}
inline void QuotaRequest::clear_guarantee() {
  guarantee_.Clear();
}
inline const ::mesos::Resource& QuotaRequest::guarantee(int index) const {
  // @@protoc_insertion_point(field_get:mesos.quota.QuotaRequest.guarantee)
  return guarantee_.Get(index);
}
inline ::mesos::Resource* QuotaRequest::mutable_guarantee(int index) {
  // @@protoc_insertion_point(field_mutable:mesos.quota.QuotaRequest.guarantee)
  return guarantee_.Mutable(index);
}
inline ::mesos::Resource* QuotaRequest::add_guarantee() {
  // @@protoc_insertion_point(field_add:mesos.quota.QuotaRequest.guarantee)
  return guarantee_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::mesos::Resource >&
QuotaRequest::guarantee() const {
  // @@protoc_insertion_point(field_list:mesos.quota.QuotaRequest.guarantee)
  return guarantee_;
}
inline ::google::protobuf::RepeatedPtrField< ::mesos::Resource >*
QuotaRequest::mutable_guarantee() {
  // @@protoc_insertion_point(field_mutable_list:mesos.quota.QuotaRequest.guarantee)
  return &guarantee_;
}

// -------------------------------------------------------------------

// QuotaStatus

// repeated .mesos.quota.QuotaInfo infos = 1;
inline int QuotaStatus::infos_size() const {
  return infos_.size();
}
inline void QuotaStatus::clear_infos() {
  infos_.Clear();
}
inline const ::mesos::quota::QuotaInfo& QuotaStatus::infos(int index) const {
  // @@protoc_insertion_point(field_get:mesos.quota.QuotaStatus.infos)
  return infos_.Get(index);
}
inline ::mesos::quota::QuotaInfo* QuotaStatus::mutable_infos(int index) {
  // @@protoc_insertion_point(field_mutable:mesos.quota.QuotaStatus.infos)
  return infos_.Mutable(index);
}
inline ::mesos::quota::QuotaInfo* QuotaStatus::add_infos() {
  // @@protoc_insertion_point(field_add:mesos.quota.QuotaStatus.infos)
  return infos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::mesos::quota::QuotaInfo >&
QuotaStatus::infos() const {
  // @@protoc_insertion_point(field_list:mesos.quota.QuotaStatus.infos)
  return infos_;
}
inline ::google::protobuf::RepeatedPtrField< ::mesos::quota::QuotaInfo >*
QuotaStatus::mutable_infos() {
  // @@protoc_insertion_point(field_mutable_list:mesos.quota.QuotaStatus.infos)
  return &infos_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace quota
}  // namespace mesos

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_quota_2eproto__INCLUDED
