// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quota.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "quota.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace mesos {
namespace quota {

namespace {

const ::google::protobuf::Descriptor* QuotaInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  QuotaInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* QuotaRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  QuotaRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* QuotaStatus_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  QuotaStatus_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_quota_2eproto() {
  protobuf_AddDesc_quota_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "quota.proto");
  GOOGLE_CHECK(file != NULL);
  QuotaInfo_descriptor_ = file->message_type(0);
  static const int QuotaInfo_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaInfo, role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaInfo, principal_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaInfo, guarantee_),
  };
  QuotaInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      QuotaInfo_descriptor_,
      QuotaInfo::default_instance_,
      QuotaInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(QuotaInfo));
  QuotaRequest_descriptor_ = file->message_type(1);
  static const int QuotaRequest_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaRequest, force_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaRequest, role_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaRequest, guarantee_),
  };
  QuotaRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      QuotaRequest_descriptor_,
      QuotaRequest::default_instance_,
      QuotaRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(QuotaRequest));
  QuotaStatus_descriptor_ = file->message_type(2);
  static const int QuotaStatus_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaStatus, infos_),
  };
  QuotaStatus_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      QuotaStatus_descriptor_,
      QuotaStatus::default_instance_,
      QuotaStatus_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaStatus, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(QuotaStatus, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(QuotaStatus));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_quota_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    QuotaInfo_descriptor_, &QuotaInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    QuotaRequest_descriptor_, &QuotaRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    QuotaStatus_descriptor_, &QuotaStatus::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_quota_2eproto() {
  delete QuotaInfo::default_instance_;
  delete QuotaInfo_reflection_;
  delete QuotaRequest::default_instance_;
  delete QuotaRequest_reflection_;
  delete QuotaStatus::default_instance_;
  delete QuotaStatus_reflection_;
}

void protobuf_AddDesc_quota_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::mesos::protobuf_AddDesc_mesos_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013quota.proto\022\013mesos.quota\032\013mesos.proto\""
    "P\n\tQuotaInfo\022\014\n\004role\030\001 \001(\t\022\021\n\tprincipal\030"
    "\002 \001(\t\022\"\n\tguarantee\030\003 \003(\0132\017.mesos.Resourc"
    "e\"V\n\014QuotaRequest\022\024\n\005force\030\001 \001(\010:\005false\022"
    "\014\n\004role\030\002 \001(\t\022\"\n\tguarantee\030\003 \003(\0132\017.mesos"
    ".Resource\"4\n\013QuotaStatus\022%\n\005infos\030\001 \003(\0132"
    "\026.mesos.quota.QuotaInfoB \n\026org.apache.me"
    "sos.quotaB\006Protos", 297);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "quota.proto", &protobuf_RegisterTypes);
  QuotaInfo::default_instance_ = new QuotaInfo();
  QuotaRequest::default_instance_ = new QuotaRequest();
  QuotaStatus::default_instance_ = new QuotaStatus();
  QuotaInfo::default_instance_->InitAsDefaultInstance();
  QuotaRequest::default_instance_->InitAsDefaultInstance();
  QuotaStatus::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_quota_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_quota_2eproto {
  StaticDescriptorInitializer_quota_2eproto() {
    protobuf_AddDesc_quota_2eproto();
  }
} static_descriptor_initializer_quota_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int QuotaInfo::kRoleFieldNumber;
const int QuotaInfo::kPrincipalFieldNumber;
const int QuotaInfo::kGuaranteeFieldNumber;
#endif  // !_MSC_VER

QuotaInfo::QuotaInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mesos.quota.QuotaInfo)
}

void QuotaInfo::InitAsDefaultInstance() {
}

QuotaInfo::QuotaInfo(const QuotaInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:mesos.quota.QuotaInfo)
}

void QuotaInfo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  role_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  principal_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

QuotaInfo::~QuotaInfo() {
  // @@protoc_insertion_point(destructor:mesos.quota.QuotaInfo)
  SharedDtor();
}

void QuotaInfo::SharedDtor() {
  if (role_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete role_;
  }
  if (principal_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete principal_;
  }
  if (this != default_instance_) {
  }
}

void QuotaInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* QuotaInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return QuotaInfo_descriptor_;
}

const QuotaInfo& QuotaInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_quota_2eproto();
  return *default_instance_;
}

QuotaInfo* QuotaInfo::default_instance_ = NULL;

QuotaInfo* QuotaInfo::New() const {
  return new QuotaInfo;
}

void QuotaInfo::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_role()) {
      if (role_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        role_->clear();
      }
    }
    if (has_principal()) {
      if (principal_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        principal_->clear();
      }
    }
  }
  guarantee_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool QuotaInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mesos.quota.QuotaInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string role = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_role()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->role().data(), this->role().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "role");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_principal;
        break;
      }

      // optional string principal = 2;
      case 2: {
        if (tag == 18) {
         parse_principal:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_principal()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->principal().data(), this->principal().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "principal");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_guarantee;
        break;
      }

      // repeated .mesos.Resource guarantee = 3;
      case 3: {
        if (tag == 26) {
         parse_guarantee:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_guarantee()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_guarantee;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mesos.quota.QuotaInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mesos.quota.QuotaInfo)
  return false;
#undef DO_
}

void QuotaInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mesos.quota.QuotaInfo)
  // optional string role = 1;
  if (has_role()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->role().data(), this->role().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "role");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->role(), output);
  }

  // optional string principal = 2;
  if (has_principal()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->principal().data(), this->principal().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "principal");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->principal(), output);
  }

  // repeated .mesos.Resource guarantee = 3;
  for (int i = 0; i < this->guarantee_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->guarantee(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mesos.quota.QuotaInfo)
}

::google::protobuf::uint8* QuotaInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mesos.quota.QuotaInfo)
  // optional string role = 1;
  if (has_role()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->role().data(), this->role().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "role");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->role(), target);
  }

  // optional string principal = 2;
  if (has_principal()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->principal().data(), this->principal().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "principal");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->principal(), target);
  }

  // repeated .mesos.Resource guarantee = 3;
  for (int i = 0; i < this->guarantee_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->guarantee(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mesos.quota.QuotaInfo)
  return target;
}

int QuotaInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string role = 1;
    if (has_role()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->role());
    }

    // optional string principal = 2;
    if (has_principal()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->principal());
    }

  }
  // repeated .mesos.Resource guarantee = 3;
  total_size += 1 * this->guarantee_size();
  for (int i = 0; i < this->guarantee_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->guarantee(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void QuotaInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const QuotaInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const QuotaInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void QuotaInfo::MergeFrom(const QuotaInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  guarantee_.MergeFrom(from.guarantee_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_role()) {
      set_role(from.role());
    }
    if (from.has_principal()) {
      set_principal(from.principal());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void QuotaInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void QuotaInfo::CopyFrom(const QuotaInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QuotaInfo::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->guarantee())) return false;
  return true;
}

void QuotaInfo::Swap(QuotaInfo* other) {
  if (other != this) {
    std::swap(role_, other->role_);
    std::swap(principal_, other->principal_);
    guarantee_.Swap(&other->guarantee_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata QuotaInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = QuotaInfo_descriptor_;
  metadata.reflection = QuotaInfo_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int QuotaRequest::kForceFieldNumber;
const int QuotaRequest::kRoleFieldNumber;
const int QuotaRequest::kGuaranteeFieldNumber;
#endif  // !_MSC_VER

QuotaRequest::QuotaRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mesos.quota.QuotaRequest)
}

void QuotaRequest::InitAsDefaultInstance() {
}

QuotaRequest::QuotaRequest(const QuotaRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:mesos.quota.QuotaRequest)
}

void QuotaRequest::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  force_ = false;
  role_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

QuotaRequest::~QuotaRequest() {
  // @@protoc_insertion_point(destructor:mesos.quota.QuotaRequest)
  SharedDtor();
}

void QuotaRequest::SharedDtor() {
  if (role_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete role_;
  }
  if (this != default_instance_) {
  }
}

void QuotaRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* QuotaRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return QuotaRequest_descriptor_;
}

const QuotaRequest& QuotaRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_quota_2eproto();
  return *default_instance_;
}

QuotaRequest* QuotaRequest::default_instance_ = NULL;

QuotaRequest* QuotaRequest::New() const {
  return new QuotaRequest;
}

void QuotaRequest::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    force_ = false;
    if (has_role()) {
      if (role_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        role_->clear();
      }
    }
  }
  guarantee_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool QuotaRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mesos.quota.QuotaRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool force = 1 [default = false];
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &force_)));
          set_has_force();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_role;
        break;
      }

      // optional string role = 2;
      case 2: {
        if (tag == 18) {
         parse_role:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_role()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->role().data(), this->role().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "role");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_guarantee;
        break;
      }

      // repeated .mesos.Resource guarantee = 3;
      case 3: {
        if (tag == 26) {
         parse_guarantee:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_guarantee()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_guarantee;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mesos.quota.QuotaRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mesos.quota.QuotaRequest)
  return false;
#undef DO_
}

void QuotaRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mesos.quota.QuotaRequest)
  // optional bool force = 1 [default = false];
  if (has_force()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->force(), output);
  }

  // optional string role = 2;
  if (has_role()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->role().data(), this->role().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "role");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->role(), output);
  }

  // repeated .mesos.Resource guarantee = 3;
  for (int i = 0; i < this->guarantee_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->guarantee(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mesos.quota.QuotaRequest)
}

::google::protobuf::uint8* QuotaRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mesos.quota.QuotaRequest)
  // optional bool force = 1 [default = false];
  if (has_force()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->force(), target);
  }

  // optional string role = 2;
  if (has_role()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->role().data(), this->role().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "role");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->role(), target);
  }

  // repeated .mesos.Resource guarantee = 3;
  for (int i = 0; i < this->guarantee_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->guarantee(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mesos.quota.QuotaRequest)
  return target;
}

int QuotaRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool force = 1 [default = false];
    if (has_force()) {
      total_size += 1 + 1;
    }

    // optional string role = 2;
    if (has_role()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->role());
    }

  }
  // repeated .mesos.Resource guarantee = 3;
  total_size += 1 * this->guarantee_size();
  for (int i = 0; i < this->guarantee_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->guarantee(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void QuotaRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const QuotaRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const QuotaRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void QuotaRequest::MergeFrom(const QuotaRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  guarantee_.MergeFrom(from.guarantee_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_force()) {
      set_force(from.force());
    }
    if (from.has_role()) {
      set_role(from.role());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void QuotaRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void QuotaRequest::CopyFrom(const QuotaRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QuotaRequest::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->guarantee())) return false;
  return true;
}

void QuotaRequest::Swap(QuotaRequest* other) {
  if (other != this) {
    std::swap(force_, other->force_);
    std::swap(role_, other->role_);
    guarantee_.Swap(&other->guarantee_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata QuotaRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = QuotaRequest_descriptor_;
  metadata.reflection = QuotaRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int QuotaStatus::kInfosFieldNumber;
#endif  // !_MSC_VER

QuotaStatus::QuotaStatus()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mesos.quota.QuotaStatus)
}

void QuotaStatus::InitAsDefaultInstance() {
}

QuotaStatus::QuotaStatus(const QuotaStatus& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:mesos.quota.QuotaStatus)
}

void QuotaStatus::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

QuotaStatus::~QuotaStatus() {
  // @@protoc_insertion_point(destructor:mesos.quota.QuotaStatus)
  SharedDtor();
}

void QuotaStatus::SharedDtor() {
  if (this != default_instance_) {
  }
}

void QuotaStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* QuotaStatus::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return QuotaStatus_descriptor_;
}

const QuotaStatus& QuotaStatus::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_quota_2eproto();
  return *default_instance_;
}

QuotaStatus* QuotaStatus::default_instance_ = NULL;

QuotaStatus* QuotaStatus::New() const {
  return new QuotaStatus;
}

void QuotaStatus::Clear() {
  infos_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool QuotaStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mesos.quota.QuotaStatus)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .mesos.quota.QuotaInfo infos = 1;
      case 1: {
        if (tag == 10) {
         parse_infos:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_infos()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_infos;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mesos.quota.QuotaStatus)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mesos.quota.QuotaStatus)
  return false;
#undef DO_
}

void QuotaStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mesos.quota.QuotaStatus)
  // repeated .mesos.quota.QuotaInfo infos = 1;
  for (int i = 0; i < this->infos_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->infos(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mesos.quota.QuotaStatus)
}

::google::protobuf::uint8* QuotaStatus::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mesos.quota.QuotaStatus)
  // repeated .mesos.quota.QuotaInfo infos = 1;
  for (int i = 0; i < this->infos_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->infos(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mesos.quota.QuotaStatus)
  return target;
}

int QuotaStatus::ByteSize() const {
  int total_size = 0;

  // repeated .mesos.quota.QuotaInfo infos = 1;
  total_size += 1 * this->infos_size();
  for (int i = 0; i < this->infos_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->infos(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void QuotaStatus::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const QuotaStatus* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const QuotaStatus*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void QuotaStatus::MergeFrom(const QuotaStatus& from) {
  GOOGLE_CHECK_NE(&from, this);
  infos_.MergeFrom(from.infos_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void QuotaStatus::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void QuotaStatus::CopyFrom(const QuotaStatus& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QuotaStatus::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->infos())) return false;
  return true;
}

void QuotaStatus::Swap(QuotaStatus* other) {
  if (other != this) {
    infos_.Swap(&other->infos_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata QuotaStatus::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = QuotaStatus_descriptor_;
  metadata.reflection = QuotaStatus_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace quota
}  // namespace mesos

// @@protoc_insertion_point(global_scope)
